safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
url: http://brittcrawford.com
paginate: 5

description: "The personal blog of Britt Crawford."
root_desc: "BrittCrawford.com"
enable_comments: false

source:      .
destination: ./_site
plugins:     ./_plugins
exclude: ['deploy.sh','README.md','docs','Rakefile','Gemfile','Gemfile.lock','.gitignore']

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   pretty

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
