siteTitle="brittcrawford.com"
linkPrefix = "/"
favicon = "/img/favicon.ico"
description = "The personal site of Britt Crawford"
link = "http://brittcrawford.com/"

[author]
fullName = "Britt Crawford"
email = "britt@illtemper.org"

[reading]
api_url = "https://sheetsu.com/apis/492051fa"
google_sheet_id = "1dFrxOeknJy1nfS85eVhWROR3U9nFF3Zl8qOiOqHxfBY"
