name: Generate Documentation Style Guide

on:
  # Run on installation (when workflow file is first created)
  create:

  workflow_call:
    inputs:
      commit-styleguide:
        description: 'Commit the generated style guide to the repository'
        required: false
        default: true
        type: boolean
    secrets:
      OPENAI_API_KEY:
        description: 'OpenAI API key for enhanced AI-powered analysis'
        required: false
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for enhanced AI-powered analysis'
        required: false
  
  # Run on push to default branch
  push:
    branches: [ $default-branch ]
    paths:
      - '.github/workflows/styleguide.yml'
      - '.doc.holiday/trigger-paths.txt'
      - 'docs/**'
      - '*.md'
      - '**/*.md'
      - '**/*.mdx'
  
  # Run on pull requests to default branch
  pull_request:
    branches: [ $default-branch ]
    paths:
      - 'docs/**'
      - '*.md'
      - '**/*.md'
      - '**/*.mdx'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      commit-styleguide:
        description: 'Commit the generated style guide to the repository'
        required: false
        default: true
        type: boolean

jobs:
  generate-styleguide:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Initialize Doc Holiday Config
        uses: ./.github/actions/styleguide-action/initialize-doc-holiday-config
        id: init-config
      
      - name: Identify Documentation Framework
        uses: ./.github/actions/styleguide-action/identify-publishing-framework
        id: identify-framework
      
      - name: Detect Documentation Root
        uses: ./.github/actions/styleguide-action/detect-documentation-root
        id: detect-root
        
      - name: Generate Style Guide
        uses: ./.github/actions/styleguide-action/generate-styleguide
        with:
          output-path: '.doc.holiday/styleguide.md'
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Commit Style Guide
        if: |
          github.event_name != 'pull_request' && 
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch) &&
          (github.event_name != 'workflow_dispatch' || github.event.inputs.commit-styleguide == 'true')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          BRANCH_NAME="chore/styleguide-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .doc.holiday/
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git commit -m "docs: update style guide and config [skip ci]"
            git push origin $BRANCH_NAME
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
        id: commit-styleguide
      
      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' && 
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch) &&
          (github.event_name != 'workflow_dispatch' || github.event.inputs.commit-styleguide == 'true') &&
          steps.commit-styleguide.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-styleguide.outputs.branch_name }}
          base: ${{ github.event.repository.default_branch }}
          title: "docs: update style guide and configuration"
          body: |
            This PR contains an automated update to the documentation style guide and configuration.
            
            **Changes:**
            - Updated style guide based on current codebase analysis
            - Refreshed documentation configuration
            
            This is an automated update generated by the styleguide-action workflow.
          draft: false
          delete-branch: false

          
      - name: Check generated files
        id: check-styleguide
        run: |
          if [ -d .doc.holiday ]; then
            echo "Found .doc.holiday directory with contents:"
            ls -la .doc.holiday/
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No .doc.holiday directory found - action may have failed"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload Style Guide Artifact
        if: steps.check-styleguide.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: styleguide
          path: .doc.holiday
          include-hidden-files: true
